<?php
declare(strict_types=1);

namespace Rungud\Install;

/**
 * The plugin's own tables — only what the site does not have (PROMPT.md §2).
 * Everything else (users, orders, products, memberships, licences, coupons) is
 * read live and never copied here.
 *
 * Conventions: money DECIMAL(12,2) + CHAR(3) currency; JSON in LONGTEXT;
 * timestamps DATETIME in UTC; no table has a hard-delete path — rows are
 * archived, cancelled or revoked with actor and reason.
 */
final class Schema {

	public const DB_VERSION = '1';
	public const OPTION     = 'rungud_db_version';

	/** @return list<string> table names without prefix */
	public static function tables(): array {
		return array_keys( self::definitions() );
	}

	public static function table( string $name ): string {
		global $wpdb;
		return $wpdb->prefix . 'rungud_' . $name;
	}

	public static function install(): void {
		global $wpdb;
		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		$charset = $wpdb->get_charset_collate();
		foreach ( self::definitions() as $name => $columns ) {
			dbDelta( 'CREATE TABLE ' . self::table( $name ) . " (\n{$columns}\n) {$charset};" );
		}
		Seed::run();
		update_option( self::OPTION, self::DB_VERSION, false );
	}

	/** @return array<string,string> dbDelta column blocks (two spaces before PRIMARY KEY is required by dbDelta). */
	private static function definitions(): array {
		return array(
			'audit'             => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  created_at datetime NOT NULL,
  actor_id bigint(20) unsigned NULL,
  actor_label varchar(190) NOT NULL DEFAULT '',
  entity varchar(40) NOT NULL,
  entity_id varchar(64) NOT NULL DEFAULT '',
  action varchar(60) NOT NULL,
  status varchar(12) NOT NULL DEFAULT 'ok',
  error text NULL,
  before_json longtext NULL,
  after_json longtext NULL,
  summary_en text NOT NULL,
  summary_de text NOT NULL,
  request_id char(36) NULL,
  retry_of bigint(20) unsigned NULL,
  PRIMARY KEY  (id),
  KEY entity (entity,entity_id),
  KEY status (status,created_at),
  KEY retry_of (retry_of),
  UNIQUE KEY request_id (request_id)",

			'sessions'          => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  user_id bigint(20) unsigned NOT NULL,
  family char(36) NOT NULL,
  token_hash char(64) NOT NULL,
  created_at datetime NOT NULL,
  expires_at datetime NOT NULL,
  revoked_at datetime NULL,
  revoked_reason varchar(40) NULL,
  ip varchar(45) NOT NULL DEFAULT '',
  user_agent varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY  (id),
  UNIQUE KEY token_hash (token_hash),
  KEY family (family),
  KEY user_id (user_id)",

			'settings'          => "setting_key varchar(80) NOT NULL,
  value_json longtext NOT NULL,
  updated_by bigint(20) unsigned NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY  (setting_key)",

			'legal_entities'    => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  name varchar(190) NOT NULL,
  owner_name varchar(190) NOT NULL DEFAULT '',
  street varchar(190) NOT NULL DEFAULT '',
  postal_code varchar(20) NOT NULL DEFAULT '',
  city varchar(120) NOT NULL DEFAULT '',
  country char(2) NOT NULL DEFAULT 'CH',
  vat_number varchar(40) NOT NULL DEFAULT '',
  tax_number varchar(40) NOT NULL DEFAULT '',
  iban varchar(40) NOT NULL DEFAULT '',
  bic varchar(20) NOT NULL DEFAULT '',
  bank_name varchar(120) NOT NULL DEFAULT '',
  email varchar(190) NOT NULL DEFAULT '',
  website varchar(190) NOT NULL DEFAULT '',
  currency_default char(3) NOT NULL DEFAULT 'EUR',
  footer_en text NULL,
  footer_de text NULL,
  archived_at datetime NULL,
  PRIMARY KEY  (id)",

			'vat_profiles'      => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  code varchar(40) NOT NULL,
  name_en varchar(120) NOT NULL,
  name_de varchar(120) NOT NULL,
  country char(2) NULL,
  rate decimal(5,2) NOT NULL,
  treatment varchar(20) NOT NULL,
  note_en text NULL,
  note_de text NULL,
  explanation_en text NULL,
  explanation_de text NULL,
  archived_at datetime NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY code (code)",

			'number_sequences'  => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  doc_type varchar(20) NOT NULL,
  legal_entity_id bigint(20) unsigned NOT NULL,
  prefix varchar(20) NOT NULL DEFAULT '',
  next_number bigint(20) unsigned NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY doc_type (doc_type,legal_entity_id)",

			'cancellation_terms' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  code varchar(40) NOT NULL,
  name varchar(190) NOT NULL,
  version int(10) unsigned NOT NULL,
  valid_from date NOT NULL,
  applies_to varchar(20) NULL,
  bands_json longtext NOT NULL,
  basis varchar(20) NOT NULL DEFAULT 'total_price',
  transfer_allowed tinyint(1) NOT NULL DEFAULT 1,
  transfer_min_days int(10) unsigned NOT NULL DEFAULT 7,
  health_declaration_hours int(10) unsigned NOT NULL DEFAULT 72,
  text_en longtext NULL,
  text_de longtext NULL,
  created_at datetime NOT NULL,
  archived_at datetime NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY code_version (code,version)",

			'invoices'          => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  number varchar(40) NULL,
  kind varchar(20) NOT NULL DEFAULT 'invoice',
  status varchar(20) NOT NULL DEFAULT 'draft',
  legal_entity_id bigint(20) unsigned NOT NULL,
  user_id bigint(20) unsigned NULL,
  billing_snapshot longtext NULL,
  lines_json longtext NULL,
  vat_profile_id bigint(20) unsigned NULL,
  vat_profile_snapshot longtext NULL,
  language char(2) NOT NULL DEFAULT 'de',
  currency char(3) NOT NULL DEFAULT 'EUR',
  subtotal decimal(12,2) NOT NULL DEFAULT 0,
  discount_total decimal(12,2) NOT NULL DEFAULT 0,
  net_total decimal(12,2) NOT NULL DEFAULT 0,
  vat_amount decimal(12,2) NOT NULL DEFAULT 0,
  gross_total decimal(12,2) NOT NULL DEFAULT 0,
  issue_date date NULL,
  due_date date NULL,
  pdf_path varchar(255) NULL,
  woo_order_id bigint(20) unsigned NULL,
  stripe_invoice_id varchar(64) NULL,
  parent_id bigint(20) unsigned NULL,
  recipient_email varchar(190) NULL,
  internal_note text NULL,
  created_by bigint(20) unsigned NULL,
  created_at datetime NOT NULL,
  approved_by bigint(20) unsigned NULL,
  approved_at datetime NULL,
  cancelled_by bigint(20) unsigned NULL,
  cancelled_at datetime NULL,
  cancel_reason text NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY number (number),
  KEY status (status),
  KEY user_id (user_id),
  KEY parent_id (parent_id)",

			'payments'          => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  invoice_id bigint(20) unsigned NOT NULL,
  amount decimal(12,2) NOT NULL,
  currency char(3) NOT NULL,
  paid_on date NOT NULL,
  method varchar(20) NOT NULL,
  reference varchar(190) NOT NULL DEFAULT '',
  note text NULL,
  recorded_by bigint(20) unsigned NOT NULL,
  recorded_at datetime NOT NULL,
  voided_by bigint(20) unsigned NULL,
  voided_at datetime NULL,
  void_reason text NULL,
  PRIMARY KEY  (id),
  KEY invoice_id (invoice_id)",

			'refunds'           => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  status varchar(20) NOT NULL DEFAULT 'prepared',
  method varchar(20) NOT NULL,
  amount decimal(12,2) NOT NULL,
  currency char(3) NOT NULL,
  credit_note_id bigint(20) unsigned NULL,
  woo_order_id bigint(20) unsigned NULL,
  stripe_ref varchar(64) NULL,
  iban varchar(40) NULL,
  reference varchar(190) NOT NULL DEFAULT '',
  reason text NULL,
  prepared_by bigint(20) unsigned NOT NULL,
  prepared_at datetime NOT NULL,
  executed_by bigint(20) unsigned NULL,
  executed_at datetime NULL,
  cancelled_by bigint(20) unsigned NULL,
  cancelled_at datetime NULL,
  PRIMARY KEY  (id),
  KEY credit_note_id (credit_note_id),
  KEY woo_order_id (woo_order_id)",

			'certificates'      => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  number varchar(40) NOT NULL,
  licence_number varchar(40) NULL,
  user_id bigint(20) unsigned NULL,
  participant_name varchar(190) NOT NULL,
  participant_email varchar(190) NULL,
  program_slug varchar(120) NOT NULL,
  completed_on date NOT NULL,
  days decimal(5,1) NULL,
  place varchar(190) NULL,
  trainer varchar(190) NULL,
  valid_until date NULL,
  language char(2) NOT NULL DEFAULT 'de',
  status varchar(20) NOT NULL DEFAULT 'valid',
  supersedes_id bigint(20) unsigned NULL,
  pdf_path varchar(255) NULL,
  issued_by bigint(20) unsigned NULL,
  issued_at datetime NOT NULL,
  revoked_by bigint(20) unsigned NULL,
  revoked_at datetime NULL,
  revoke_reason text NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY number (number),
  KEY licence_number (licence_number),
  KEY user_id (user_id),
  KEY program_slug (program_slug)",

			'education_history' => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  user_id bigint(20) unsigned NULL,
  participant_email varchar(190) NULL,
  program_slug varchar(120) NOT NULL,
  event_ref varchar(64) NULL,
  product_id bigint(20) unsigned NULL,
  woo_order_item_id bigint(20) unsigned NULL,
  completed_on date NOT NULL,
  source varchar(20) NOT NULL,
  certificate_id bigint(20) unsigned NULL,
  import_batch varchar(36) NULL,
  created_by bigint(20) unsigned NULL,
  created_at datetime NOT NULL,
  archived_at datetime NULL,
  archive_reason text NULL,
  PRIMARY KEY  (id),
  KEY user_id (user_id),
  KEY participant_email (participant_email),
  KEY program_slug (program_slug)",

			'discount_codes'    => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  code varchar(40) NOT NULL,
  woo_coupon_id bigint(20) unsigned NULL,
  kind varchar(20) NOT NULL,
  pct decimal(5,2) NULL,
  program_slugs longtext NULL,
  one_per_person tinyint(1) NOT NULL DEFAULT 1,
  stackable tinyint(1) NOT NULL DEFAULT 0,
  for_label varchar(190) NULL,
  note text NULL,
  promised_by bigint(20) unsigned NULL,
  made_by bigint(20) unsigned NOT NULL,
  made_at datetime NOT NULL,
  sent_via varchar(20) NULL,
  sent_at datetime NULL,
  revoked_by bigint(20) unsigned NULL,
  revoked_at datetime NULL,
  revoke_reason text NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY code (code),
  KEY woo_coupon_id (woo_coupon_id)",

			'code_claims'       => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  user_id bigint(20) unsigned NULL,
  email varchar(190) NOT NULL DEFAULT '',
  name varchar(190) NOT NULL DEFAULT '',
  claim_text text NOT NULL,
  context varchar(190) NULL,
  status varchar(20) NOT NULL DEFAULT 'open',
  resulting_pct decimal(5,2) NULL,
  resulting_code_id bigint(20) unsigned NULL,
  created_by bigint(20) unsigned NULL,
  created_at datetime NOT NULL,
  decided_by bigint(20) unsigned NULL,
  decided_at datetime NULL,
  decision_note text NULL,
  PRIMARY KEY  (id),
  KEY status (status)",

			'document_sends'    => "id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  doc_type varchar(30) NOT NULL,
  doc_ref varchar(64) NOT NULL,
  to_email varchar(190) NOT NULL,
  language char(2) NOT NULL,
  subject varchar(255) NOT NULL,
  body longtext NOT NULL,
  status varchar(20) NOT NULL,
  error text NULL,
  sent_by bigint(20) unsigned NOT NULL,
  sent_at datetime NOT NULL,
  audit_id bigint(20) unsigned NULL,
  PRIMARY KEY  (id),
  KEY doc (doc_type,doc_ref)",
		);
	}
}
